# GitHub Sponsors
github: Rohit30Confluence

# Uncomment and configure these if you use them.

# patreon: your-patreon
# open_collective: your-open-collective
# ko_fi: your-kofi
# tidelift: your-tidelift
# community_bridge: your-community-bridge
# liberapay: your-liberapay
# issuehunt: your-issuehunt
# otechie: your-otechie
# lfx_crowdfunding: your-lfx-project
# custom:
#   - https://your-website.com/donate
#   - https://buymeacoffee.com/yourname